version: "3"

services:

  web:
    image: nginx:1.16.1
    container_name: Nginx-1.16.1
    restart: always
    ports:
      - "80:80"
    volumes:
      - ${PWD}/nginx:/etc/nginx/conf.d
      - ${PWD}/logs/nginx:/var/log/nginx
      - ${PWD}/code:/var/www/html
    links:
      - wordpress

  db:
    image: mariadb:10.4.8
    container_name: MariaDB-10.4.8
    restart: always
    volumes:
      - ${PWD}/db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:5.2.4-php7.3-fpm
    container_name: Wordpress-5.2.4-PHP7.3-FPM
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ${PWD}/code:/var/www/html
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_PASSWORD: wordpress
    links:
      - db
